const mockProfiles = [
  {
    id: "PR001",
    name: "Priyanjali Sharma",
    gender: "female",
    age: 26,
    dob: "1999-08-15",
    religion: "Hindu",
    caste: "Brahmin",
    motherTongue: "Hindi",
    location: "Mumbai, India",
    height: "5'5\"",
    education: "MBA, IIM Ahmedabad",
    profession: "Senior Brand Manager",
    company: "Hindustan Unilever",
    income: "₹25 - 35 Lakhs",
    incomeValue: 3000000,
    lifestyle: "Vegetarian",
    diet: "Vegetarian",
    drink: "Socially",
    smoke: "No",
    verified: { mobile: true, id: true, education: true },
    photo: "assets/bride_featured.png",
    bio: "Passionate brand strategist and classical Kathak dancer. I balance my corporate career with a deep love for Indian heritage, travel, and baking. Looking for a partner who is intellectual, values-driven, and supportive of career ambitions.",
    familyDetails: "Father is a retired IAS Officer, Mother is a Homemaker. One elder brother married and settled in the UK.",
    partnerExpectations: {
      minAge: 26,
      maxAge: 32,
      religion: "Hindu",
      motherTongue: "Hindi",
      education: "Post Graduate / MBA / Tech",
      minIncome: 2500000,
      lifestyle: "Vegetarian"
    }
  },
  {
    id: "PR002",
    name: "Rohan Malhotra",
    gender: "male",
    age: 28,
    dob: "1997-11-22",
    religion: "Hindu",
    caste: "Khatri",
    motherTongue: "Punjabi",
    location: "Delhi NCR, India",
    height: "5'11\"",
    education: "B.Tech & MS in Computer Science, IIT Delhi",
    profession: "Senior Software Architect",
    company: "Google India",
    income: "₹45 - 60 Lakhs",
    incomeValue: 5500000,
    lifestyle: "Non-Vegetarian",
    diet: "Non-Vegetarian",
    drink: "Socially",
    smoke: "No",
    verified: { mobile: true, id: true, education: true },
    photo: "assets/groom_featured.png",
    bio: "Software developer by day, guitarist and avid trekker by weekend. Deeply connected to my roots and love celebrating family gatherings. Seeking an independent, warm-hearted woman who appreciates good conversations and life's simple joys.",
    familyDetails: "Father is an established Businessman (Real Estate), Mother is a Doctor (Gynecologist). Family owns business and residence in South Delhi.",
    partnerExpectations: {
      minAge: 24,
      maxAge: 29,
      religion: "Hindu",
      motherTongue: "Punjabi",
      education: "Graduate / Post Graduate",
      minIncome: 1200000,
      lifestyle: "Any"
    }
  },
  {
    id: "PR003",
    name: "Dr. Ayesha Siddiqui",
    gender: "female",
    age: 27,
    dob: "1998-04-10",
    religion: "Muslim",
    caste: "Sunni",
    motherTongue: "Urdu",
    location: "Hyderabad, India",
    height: "5'4\"",
    education: "MD in Pediatrics, Osmania Medical College",
    profession: "Consultant Pediatrician",
    company: "Apollo Hospitals",
    income: "₹18 - 25 Lakhs",
    incomeValue: 2200000,
    lifestyle: "Non-Vegetarian",
    diet: "Halal / Non-Vegetarian",
    drink: "No",
    smoke: "No",
    verified: { mobile: true, id: true, education: true },
    photo: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400",
    bio: "Dedicated medical professional passionate about child healthcare. I enjoy writing poetry, visiting museums, and voluntary community service. Searching for a respectful, educated, and kind-hearted gentleman with shared moral values.",
    familyDetails: "Father is a retired Professor of English Literature, Mother is a High School Principal. Younger sister studying Law.",
    partnerExpectations: {
      minAge: 27,
      maxAge: 33,
      religion: "Muslim",
      motherTongue: "Urdu",
      education: "Doctor / PG / Tech / Professional",
      minIncome: 1500000,
      lifestyle: "Any"
    }
  },
  {
    id: "PR004",
    name: "Vikramjit Singh",
    gender: "male",
    age: 29,
    dob: "1996-06-30",
    religion: "Sikh",
    caste: "Jat",
    motherTongue: "Punjabi",
    location: "Chandigarh, India",
    height: "6'1\"",
    education: "M.Tech in Agricultural Engineering",
    profession: "Agri-Tech Startup Founder & Landowner",
    company: "FarmTech Solutions",
    income: "₹35 - 45 Lakhs",
    incomeValue: 4000000,
    lifestyle: "Vegetarian",
    diet: "Vegetarian",
    drink: "No",
    smoke: "No",
    verified: { mobile: true, id: true, education: false },
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400",
    bio: "Blending traditional farming heritage with modern clean-tech solutions. Grounded, family-oriented, and love Punjabi folk music. I look forward to building a peaceful life with someone who shares an appreciation for nature and family values.",
    familyDetails: "Father is a progressive agriculturist holding extensive orchards. Mother is a homemaker. Elder sister married in Canada.",
    partnerExpectations: {
      minAge: 25,
      maxAge: 30,
      religion: "Sikh",
      motherTongue: "Punjabi",
      education: "Graduate / Post Graduate",
      minIncome: 500000,
      lifestyle: "Vegetarian"
    }
  },
  {
    id: "PR005",
    name: "Meera Krishnan",
    gender: "female",
    age: 25,
    dob: "2000-12-05",
    religion: "Hindu",
    caste: "Nair",
    motherTongue: "Malayalam",
    location: "Bengaluru, India",
    height: "5'3\"",
    education: "B.Des in Product Design, NID Ahmedabad",
    profession: "Lead UI/UX Designer",
    company: "Razorpay",
    income: "₹15 - 20 Lakhs",
    incomeValue: 1800000,
    lifestyle: "Non-Vegetarian",
    diet: "Non-Vegetarian",
    drink: "Socially",
    smoke: "No",
    verified: { mobile: true, id: true, education: true },
    photo: "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400",
    bio: "Creative mind, caffeine addict, and landscape photographer. I love exploring old architecture and experimenting with gourmet cuisines. Looking for a partner who is emotionally mature, open-minded, and creative at heart.",
    familyDetails: "Father is an Executive Director at a PSU, Mother is a retired Bank Manager. Family originates from Palakkad, settled in Bangalore.",
    partnerExpectations: {
      minAge: 25,
      maxAge: 30,
      religion: "Hindu",
      motherTongue: "Malayalam",
      education: "Graduate / Post Graduate / Creative Arts",
      minIncome: 1500000,
      lifestyle: "Any"
    }
  },
  {
    id: "PR006",
    name: "Aditya D’Souza",
    gender: "male",
    age: 30,
    dob: "1995-09-14",
    religion: "Christian",
    caste: "Roman Catholic",
    motherTongue: "English",
    location: "Goa, India",
    height: "5'10\"",
    education: "Bachelor of Fine Arts & MBA, NMIMS Mumbai",
    profession: "Boutique Resort Owner & Architect",
    company: "Casa de Sol Resorts",
    income: "₹50 Lakhs+",
    incomeValue: 6000000,
    lifestyle: "Non-Vegetarian",
    diet: "Non-Vegetarian",
    drink: "Socially",
    smoke: "No",
    verified: { mobile: true, id: true, education: true },
    photo: "https://images.unsplash.com/photo-1620122303020-43ec4b6cf7f8?auto=format&fit=crop&q=80&w=400",
    bio: "Passionate about restoration architecture and conserving Goan heritage. Love sailing, jazz evenings, and hosting friends. I am searching for a warm, conversationalist, and progressive woman who would love life by the coast.",
    familyDetails: "Father is a retired Merchant Navy Captain. Mother is a writer and environmental activist. Sister is a fashion designer in Paris.",
    partnerExpectations: {
      minAge: 25,
      maxAge: 30,
      religion: "Christian",
      motherTongue: "Any",
      education: "Graduate",
      minIncome: 800000,
      lifestyle: "Any"
    }
  },
  {
    id: "PR007",
    name: "Sneha Patel",
    gender: "female",
    age: 28,
    dob: "1997-03-24",
    religion: "Hindu",
    caste: "Patel",
    motherTongue: "Gujarati",
    location: "New York, USA",
    height: "5'6\"",
    education: "MS in Data Analytics, Columbia University",
    profession: "Senior Data Scientist",
    company: "JP Morgan Chase",
    income: "$130k - $160k (NRI)",
    incomeValue: 12000000,
    lifestyle: "Vegetarian",
    diet: "Pure Vegetarian",
    drink: "No",
    smoke: "No",
    verified: { mobile: true, id: true, education: true },
    photo: "https://images.unsplash.com/photo-1594744803329-e58b31de215f?auto=format&fit=crop&q=80&w=400",
    bio: "Gujarati girl settled in NYC. Dedicated to my analytics career, but equally passionate about garba, yoga, and exploring vegetarian brunch spots. Seeking a modern, settled NRI partner with family values.",
    familyDetails: "Parents run a successful pharmaceuticals business in Ahmedabad. Elder brother is married and managing the business with father.",
    partnerExpectations: {
      minAge: 27,
      maxAge: 32,
      religion: "Hindu",
      motherTongue: "Gujarati",
      education: "MS / Post Graduate / Tech / Finance",
      minIncome: 8000000,
      lifestyle: "Vegetarian"
    }
  },
  {
    id: "PR008",
    name: "Kabir Banerjee",
    gender: "male",
    age: 31,
    dob: "1994-07-18",
    religion: "Hindu",
    caste: "Bengali Brahmin",
    motherTongue: "Bengali",
    location: "Kolkata, India",
    height: "5'9\"",
    education: "Ph.D. in Economics, London School of Economics",
    profession: "Assistant Professor",
    company: "Presidency University",
    income: "₹15 - 20 Lakhs",
    incomeValue: 1600000,
    lifestyle: "Non-Vegetarian",
    diet: "Non-Vegetarian",
    drink: "Socially",
    smoke: "No",
    verified: { mobile: true, id: true, education: true },
    photo: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400",
    bio: "Academician who loves discussions on international relations, classic cinema, and Rabindra Sangeet. Enjoy playing chess and traveling to historical sites. Looking for a well-educated, cultured, and intellectually curious partner.",
    familyDetails: "Father is an eminent retired Supreme Court Advocate. Mother is an accomplished Painter and critic. Sister works in UNESCO.",
    partnerExpectations: {
      minAge: 26,
      maxAge: 31,
      religion: "Hindu",
      motherTongue: "Bengali",
      education: "Post Graduate / Ph.D / Academic / Corporate",
      minIncome: 800000,
      lifestyle: "Any"
    }
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { mockProfiles };
}
